In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [18]:
# universal variables
sql_columns = ["dialogue_text", "actual_summary", "actual_sentiment", "dataset"]

Training Data

In [19]:
unprocessed_tr_data = pd.read_csv("flan_t5_large_labelled_train.csv")
unprocessed_tr_data.head()

,id,dialogue,summary,topic,sentiment
0,train_0,"#Person1#: Hi, Mr. Smith. I'm Doctor Hawkins. ...","Mr. Smith's getting a check-up, and Doctor Haw...",get a check-up,positive
1,train_1,"#Person1#: Hello Mrs. Parker, how have you bee...",Mrs Parker takes Ricky for his vaccines. Dr. P...,vaccines,positive
2,train_2,"#Person1#: Excuse me, did you see a set of key...",#Person1#'s looking for a set of keys and asks...,find keys,positive
3,train_3,#Person1#: Why didn't you tell me you had a gi...,#Person1#'s angry because #Person2# didn't tel...,have a girlfriend,negative
4,train_4,"#Person1#: Watsup, ladies! Y'll looking'fine t...",Malik invites Nikki to dance. Nikki agrees if ...,dance,positive

In [20]:
unprocessed_tr_data["dataset"] = "training"
processed_tr_data = unprocessed_tr_data.drop(columns = ["id", "topic"])
processed_tr_data.head()

,dialogue,summary,sentiment,dataset
0,"#Person1#: Hi, Mr. Smith. I'm Doctor Hawkins. ...","Mr. Smith's getting a check-up, and Doctor Haw...",positive,training
1,"#Person1#: Hello Mrs. Parker, how have you bee...",Mrs Parker takes Ricky for his vaccines. Dr. P...,positive,training
2,"#Person1#: Excuse me, did you see a set of key...",#Person1#'s looking for a set of keys and asks...,positive,training
3,#Person1#: Why didn't you tell me you had a gi...,#Person1#'s angry because #Person2# didn't tel...,negative,training
4,"#Person1#: Watsup, ladies! Y'll looking'fine t...",Malik invites Nikki to dance. Nikki agrees if ...,positive,training

In [21]:
# change names to match sql column names
processed_tr_data.columns = sql_columns
processed_tr_data.head()

,dialogue_text,actual_summary,actual_sentiment,dataset
0,"#Person1#: Hi, Mr. Smith. I'm Doctor Hawkins. ...","Mr. Smith's getting a check-up, and Doctor Haw...",positive,training
1,"#Person1#: Hello Mrs. Parker, how have you bee...",Mrs Parker takes Ricky for his vaccines. Dr. P...,positive,training
2,"#Person1#: Excuse me, did you see a set of key...",#Person1#'s looking for a set of keys and asks...,positive,training
3,#Person1#: Why didn't you tell me you had a gi...,#Person1#'s angry because #Person2# didn't tel...,negative,training
4,"#Person1#: Watsup, ladies! Y'll looking'fine t...",Malik invites Nikki to dance. Nikki agrees if ...,positive,training

Test Data

In [22]:
unprocessed_te_data = pd.read_csv("test.csv")
unprocessed_te_data.head()

,id,dialogue,summary,topic
0,test_0_1,"#Person1#: Ms. Dawson, I need you to take a di...",Ms. Dawson helps #Person1# to write a memo to ...,communication method
1,test_0_2,"#Person1#: Ms. Dawson, I need you to take a di...",In order to prevent employees from wasting tim...,company policy
2,test_0_3,"#Person1#: Ms. Dawson, I need you to take a di...",Ms. Dawson takes a dictation for #Person1# abo...,dictation
3,test_1_1,#Person1#: You're finally here! What took so l...,#Person2# arrives late because of traffic jam....,public transportation
4,test_1_2,#Person1#: You're finally here! What took so l...,#Person2# decides to follow #Person1#'s sugges...,transportation

In [23]:
processed_te_data = unprocessed_te_data.drop(columns=["id", "topic"])
processed_te_data["actual_sentiment"] = None
processed_te_data["dataset"] = "test"
processed_te_data.columns = sql_columns
processed_te_data.head()

,dialogue_text,actual_summary,actual_sentiment,dataset
0,"#Person1#: Ms. Dawson, I need you to take a di...",Ms. Dawson helps #Person1# to write a memo to ...,None,test
1,"#Person1#: Ms. Dawson, I need you to take a di...",In order to prevent employees from wasting tim...,None,test
2,"#Person1#: Ms. Dawson, I need you to take a di...",Ms. Dawson takes a dictation for #Person1# abo...,None,test
3,#Person1#: You're finally here! What took so l...,#Person2# arrives late because of traffic jam....,None,test
4,#Person1#: You're finally here! What took so l...,#Person2# decides to follow #Person1#'s sugges...,None,test

Validation

In [24]:
unprocessed_val_data = pd.read_csv("validation.csv")
unprocessed_val_data.head()

,id,dialogue,summary,topic
0,dev_0,"#Person1#: Hello, how are you doing today?\n#P...",#Person2# has trouble breathing. The doctor as...,see a doctor
1,dev_1,#Person1#: Hey Jimmy. Let's go workout later t...,#Person1# invites Jimmy to go workout and pers...,do exercise
2,dev_2,#Person1#: I need to stop eating such unhealth...,#Person1# plans to stop eating unhealthy foods...,healthy foods
3,dev_3,#Person1#: Do you believe in UFOs?\n#Person2#:...,#Person2# believes in UFOs and can see them in...,UFOs and aliens
4,dev_4,#Person1#: Did you go to school today?\n#Perso...,#Person1# didn't go to school today. #Person2#...,go to school

In [25]:
processed_val_data = unprocessed_val_data.drop(columns=["id", "topic"])
processed_val_data["actual_sentiment"] = None
processed_val_data["dataset"] = "valid"
processed_val_data.columns = sql_columns
processed_val_data.head()

,dialogue_text,actual_summary,actual_sentiment,dataset
0,"#Person1#: Hello, how are you doing today?\n#P...",#Person2# has trouble breathing. The doctor as...,None,valid
1,#Person1#: Hey Jimmy. Let's go workout later t...,#Person1# invites Jimmy to go workout and pers...,None,valid
2,#Person1#: I need to stop eating such unhealth...,#Person1# plans to stop eating unhealthy foods...,None,valid
3,#Person1#: Do you believe in UFOs?\n#Person2#:...,#Person2# believes in UFOs and can see them in...,None,valid
4,#Person1#: Did you go to school today?\n#Perso...,#Person1# didn't go to school today. #Person2#...,None,valid

Combine Data Sets

In [26]:
# combine all the data to one df
combined_dialogues = pd.concat([processed_tr_data, processed_te_data, processed_val_data], ignore_index=True)
combined_dialogues.head()

,dialogue_text,actual_summary,actual_sentiment,dataset
0,"#Person1#: Hi, Mr. Smith. I'm Doctor Hawkins. ...","Mr. Smith's getting a check-up, and Doctor Haw...",positive,training
1,"#Person1#: Hello Mrs. Parker, how have you bee...",Mrs Parker takes Ricky for his vaccines. Dr. P...,positive,training
2,"#Person1#: Excuse me, did you see a set of key...",#Person1#'s looking for a set of keys and asks...,positive,training
3,#Person1#: Why didn't you tell me you had a gi...,#Person1#'s angry because #Person2# didn't tel...,negative,training
4,"#Person1#: Watsup, ladies! Y'll looking'fine t...",Malik invites Nikki to dance. Nikki agrees if ...,positive,training

In [27]:
# verify by checking if rows of combined dialogues is equal to tr + te + valid
print(f"Combined_dialogues has {len(combined_dialogues)} rows")
print(f"tr({len(processed_tr_data)}) + te({len(processed_te_data)}) + validation({len(processed_val_data)}) has {len(processed_tr_data) + len(processed_te_data) + len(processed_val_data)} rows")

Combined_dialogues has 14427 rows
tr(12427) + te(1500) + validation(500) has 14427 rows

Connect to Postgre server

In [28]:
# connect to postgre database
engine = create_engine('postgresql+psycopg2://postgres:mypassword@copilot.craoqkiqslyh.us-east-2.rds.amazonaws.com:5432/copilot-db')

In [31]:
# add data to server
from sqlalchemy import text, types

with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS dialogues CASCADE"))
    conn.execute(text("CREATE TABLE dialogues( \
        dialogue_id SERIAL PRIMARY KEY, \
        dataset VARCHAR(10) NOT NULL, \
        dialogue_text TEXT NOT NULL, \
        actual_summary TEXT NOT NULL, \
        actual_sentiment VARCHAR(8));"))
    processed_tr_data.to_sql('dialogues', con = conn, if_exists='append', index=False, method='multi',
                             chunksize=1000, dtype={"dialogue_text":types.TEXT, "dataset": types.VARCHAR(10), 
                                                    "actual_summary":types.TEXT, "actual_sentiment":types.VARCHAR(8)})